### PR TITLE
Fix panic when transposing with no text or at EOF

### LINKED ISSUE #962: Crash on transpose at EOF
On xi-mac:

- create a new document, with the contents `word\n`.
- put the cursor on the second (empty) line
- cmd + click the end of the first line (two cursors)
- ctrl + t to transpose

```
thread 'main' panicked at 'Delta builder: intervals not properly sorted', rope/src/delta.rs:572:9
stack backtrace:
   0:        0x100aa737f - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h6860ca4858977c58
   1:        0x100a945cd - std::sys_common::backtrace::print::hfce447bb77721cd1
   2:        0x100aab7b3 - std::panicking::default_hook::{{closure}}::hdd7beb2b33ee8274
   3:        0x100aab53c - std::panicking::default_hook::h52d496fea38543eb
   4:        0x100aabee7 - std::panicking::rust_panic_with_hook::h4cb31c29ed859698
   5:        0x1009c9a47 - std::panicking::begin_panic::h03beabababc57aaf
   6:        0x1006514e7 - <xi_rope::delta::Builder<N>>::delete::h062a98716bc996d0
   7:        0x100651570 - <xi_rope::delta::Builder<N>>::replace::h99ed603dc6b1f28a
   8:        0x10027ac85 - xi_core_lib::editor::Editor::do_transpose::h5b9863de43ed1456
   9:        0x10027c638 - xi_core_lib::editor::Editor::do_edit::hf7a9fb5feef2df7b
  10:        0x10028a465 - xi_core_lib::event_context::EventContext::dispatch_event::{{closure}}::heb5f2cebb14f4ef5
  11:        0x100288e12 - xi_core_lib::event_context::EventContext::with_editor::h3f08449e977ee052
  12:        0x100595398 - xi_core_lib::event_context::EventContext::dispatch_event::hb61f8b7d85f9cf9b
  13:        0x10059517d - xi_core_lib::event_context::EventContext::do_edit::h452170c7c6d8cfe1
  14:        0x10049450c - xi_core_lib::tabs::CoreState::do_edit::h5a824b141ce4bb7b
  15:        0x10049330e - xi_core_lib::tabs::CoreState::client_notification::hca22098a5803c337
  16:        0x100247b34 - <xi_core_lib::core::XiCore as xi_rpc::Handler>::handle_notification::h791c89b09932273d
  17:        0x100119854 - <xi_rpc::RpcLoop<W>>::mainloop::{{closure}}::h1da678ab59da353c
  18:        0x10013d745 - crossbeam_utils::thread::scope::h26195b66fd402fbf
  19:        0x100118e73 - <xi_rpc::RpcLoop<W>>::mainloop::hcedcde3992d2dfcd
  20:        0x1000e1eff - xi_core::main::h774cadb65e0218f9
  21:        0x1000e5d11 - std::rt::lang_start::{{closure}}::hb9ac36939cfd6c39
  22:        0x100aab8b7 - std::panicking::try::do_call::hdc4508fe181791f6
  23:        0x100ab781e - __rust_maybe_catch_panic
  24:        0x100a9d80c - std::rt::lang_start_internal::h6d6c64041629047f
  25:        0x1000e5cf1 - std::rt::lang_start::h9b0d56e73d0001b9
  26:        0x1000e2551 - main
```

### PR DESCRIPTION
**Pull request by russelltg**
## Summary
Fix a bug where xi-core would panic when transposing (Ctrl+T) on a empty file.

Steps to reproduce:

Open any XI editor (any should work, I personally tested on xi-gtk)
Press Ctrl+T
**panic**

Or the steps described in #962.

After this fix, it follows the expected behavior of not doing anything, and not panicking.

I have added a check to make sure the `end` index is not set to anything above the length of the text, which was causing the crash. 

Additionally, I have added two tests that previously panicked and now pass.

## Related Issues
* #962: This pull request also fixes this bug

Closes #962

## Review Checklist

- [x] I have responded to reviews and made changes where appropriate.
- [x] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [x] I have updated comments / documentation related to the changes I made.
- [x] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

**Comment by cmyr** [comment]
Cool, thanks for this!

Thinking about this, I think it does make sense that transpose at EOF is a noop, because transpose requires a 'next' character.

I also wonder how transpose is currently working when line endings are `\r\n`... 😬

**Comment by russelltg** [comment]
```rust
let mut editor = Editor::with_text("word\r\n");
let mut view = View::new(1.into(), BufferId::new(2));

let mut selection = Selection::new();
selection.add_region(SelRegion::caret(4)); // end of the first line
selection.add_region(SelRegion::caret(6)); // at eof
view.set_selection(&editor.text, selection);

editor.do_transpose(&view);
```

Yields `wor\r\nd`, as expected.

File: rust/core-lib/src/editor.rs [hunk 1]
```diff
@@ -1019,4 +1021,30 @@ mod tests {
 
         assert_eq!(editor.get_buffer().to_string(), "sshello");
     }
+
+    #[test]
+    fn empty_transpose() {
```
Comment (cmyr) [inline rust/core-lib/src/editor.rs]: these tests should probably go in `event_context.rs`; there's a nice harness there for testing these kinds of commands.
