### PR TITLE
Fix new clippy lints in 1.40.

### LINKED ISSUE #1248: fix new clippy lints in 1.40
CI is failing because clippy is sad. If someone wants to patch that up they're welcome to!

### PR DESCRIPTION
**Pull request by PsiACE**
## Summary
Try to make CI pass again.
- Using `match` and `cmp` instead of `if`. https://rust-lang.github.io/rust-clippy/master/index.html#comparison_chain
- Allow needless doctest main. https://rust-lang.github.io/rust-clippy/master/index.html#needless_doctest_main
- Allow redundant clone. I don't think there's a problem here. https://rust-lang.github.io/rust-clippy/master/index.html#redundant_clone.
- s.to_string() -> (*s).to_string(), https://rust-lang.github.io/rust-clippy/master/index.html#inefficient_to_string

## Related Issues
Related to #1248 

closes #1248 

## Checklist
- [x] Pass All Checks
- [ ] Clean up commented out old code.

## Review Checklist

- [ ] I have responded to reviews and made changes where appropriate.
- [x] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [ ] I have updated comments / documentation related to the changes I made.
- [ ] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

File: rust/core-lib/src/index_set.rs [hunk 1]
```diff
@@ -18,23 +18,36 @@
...
 pub fn remove_n_at<T: Clone>(v: &mut Vec<T>, index: usize, n: usize) {
-    if n == 1 {
-        v.remove(index);
-    } else if n > 1 {
-        let new_len = v.len() - n;
-        for i in index..new_len {
-            v[i] = v[i + n].clone();
+    match n.cmp(&1) {
+        Ordering::Equal => {
+            v.remove(index);
```
Comment (cmyr) [inline rust/core-lib/src/index_set.rs]: style nit: I would leave out the braces, and just write this as,

```rust
Ordering::Equal => v.remove(index),
```

File: rust/core-lib/src/index_set.rs [hunk 2]
```diff
@@ -18,23 +18,36 @@
...
+        Ordering::Greater => {
+            let new_len = v.len() - n;
+            for i in index..new_len {
+                v[i] = v[i + n].clone();
+            }
+            v.truncate(new_len);
+        }
+        Ordering::Less => {}
     }
+    // if n == 1 {
```
Comment (cmyr) [inline rust/core-lib/src/index_set.rs]: this can be deleted.

File: rust/core-lib/src/index_set.rs [hunk 3]
```diff
@@ -18,23 +18,36 @@
...
         }
-        v.truncate(new_len);
+        Ordering::Greater => {
+            let new_len = v.len() - n;
+            for i in index..new_len {
+                v[i] = v[i + n].clone();
+            }
+            v.truncate(new_len);
+        }
+        Ordering::Less => {}
```
Comment (cmyr) [inline rust/core-lib/src/index_set.rs]: total nit: it's idiomatic to write this as,

```rust
Ordering::Less => (),
```

which implies that you are explicitly returning the unit (`()`) and not returning it implicitly with an empty block.

File: rust/core-lib/src/plugins/catalog.rs [hunk 4]
```diff
@@ -14,6 +14,8 @@
 
 //! Keeping track of available plugins.
 
+#![allow(clippy::redundant_clone)]
```
Comment (cmyr) [inline rust/core-lib/src/plugins/catalog.rs]: I think clippy is actually pointing out an actual error here; we have a `to_owned()` call on L119 of this file that we can remove.

File: rust/core-lib/src/tabs.rs [hunk 5]
```diff
@@ -19,6 +19,8 @@
 //! This file is called 'tabs' for historical reasons, and should probably
 //! be renamed.
 
+#![allow(clippy::redundant_clone)]
```
Comment (cmyr) [inline rust/core-lib/src/tabs.rs]: ditto: this is actually a reasonable catch from clippy, on L526 we call `manifest.clone()` unnecessarily.

File: rust/rope/src/multiset.rs [hunk 6]
```diff
@@ -424,21 +424,40 @@ impl<'a> Iterator for ZipIter<'a> {
...
+                        self.a_i += 1;
+                        self.a_consumed - self.consumed
+                    }
+                    cmp::Ordering::Greater => {
+                        self.b_consumed += b_len;
+                        self.b_i += 1;
+                        self.b_consumed - self.consumed
+                    }
                 };
+                // let len = if a_len + self.a_consumed == b_len + self.b_consumed {
```
Comment (cmyr) [inline rust/rope/src/multiset.rs]: 😁

File: rust/rope/src/rope.rs [hunk 7]
```diff
@@ -477,12 +479,21 @@ impl Rope {
...
+            Ordering::Greater => {
+                panic!("line number {} beyond last line {}", line, max_line);
+            }
+            Ordering::Equal => {
+                return self.len();
+            }
+            Ordering::Less => self.count_base_units::<LinesMetric>(line),
         }
-        self.count_base_units::<LinesMetric>(line)
+        // if line > max_line {
```
Comment (cmyr) [inline rust/rope/src/rope.rs]: 😁

File: rust/rope/src/spans.rs [hunk 8]
```diff
@@ -243,15 +243,30 @@ impl<T: Clone> Spans<T> {
...
+                    red_iv = red_iv.suffix(iv);
+                }
+                Ordering::Greater => {
+                    let iv = blue_iv.prefix(red_iv);
+                    sb.add_span(iv, f(blue_val, None));
+                    blue_iv = blue_iv.suffix(iv);
+                }
+                Ordering::Equal => {}
             }
+            // if red_iv.start() < blue_iv.start() {
```
Comment (cmyr) [inline rust/rope/src/spans.rs]: 😁

File: rust/core-lib/src/rpc.rs [hunk 9]
```diff
@@ -18,6 +18,8 @@
 //! the JSON-RPC protocol and the types here.
 //!
 //! [Serde]: https://serde.rs
+#![allow(clippy::needless_doctest_main)]
```
Comment (cmyr) [inline rust/core-lib/src/rpc.rs]: this can also just be fixed, by removing the `# fn main() {` line from these various doctests; I think it was required at some point.

File: rust/rpc/src/error.rs [hunk 10]
```diff
@@ -12,6 +12,8 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+#![allow(clippy::needless_doctest_main)]
```
Comment (cmyr) [inline rust/rpc/src/error.rs]: again we can just fix this.

File: rust/unicode/src/lib.rs [hunk 11]
```diff
@@ -72,26 +72,53 @@ impl<'a> Iterator for LineBreakIterator<'a> {
...
-            //println!("\"{}\"[{}], state {} + lb {} -> {}", &self.s[self.ix..], self.ix, self.state, lb, new);
-            let result = self.ix;
-            self.ix += len;
-            if (new as i8) < 0 {
-                // break found
-                self.state = new & 0x3f;
-                return Some((result, new >= 0xc0));
-            } else {
-                self.state = new;
+            use std::cmp::Ordering;
```
Comment (cmyr) [inline rust/unicode/src/lib.rs]: I would move this to the top of the function, outside the loop (doesn't matter but is more idiomatic)

File: rust/unicode/src/lib.rs [hunk 12]
```diff
@@ -72,26 +72,53 @@ impl<'a> Iterator for LineBreakIterator<'a> {
...
+                    if (new as i8) < 0 {
+                        // break found
+                        self.state = new & 0x3f;
+                        return Some((result, new >= 0xc0));
+                    } else {
+                        self.state = new;
+                    }
+                }
             }
+            // if self.ix > self.s.len() {
```
Comment (cmyr) [inline rust/unicode/src/lib.rs]: ✂️

File: rust/core-lib/src/index_set.rs (hunk 1 above)
Comment (PsiACE) [reply rust/core-lib/src/index_set.rs]: Get an error `error[E0308]: match arms have incompatible types`
Honestly, I keep it for the time being.

File: rust/core-lib/src/index_set.rs (hunk 2 above)
Comment (PsiACE) [reply rust/core-lib/src/index_set.rs]: :ok_hand:

File: rust/core-lib/src/index_set.rs (hunk 3 above)
Comment (PsiACE) [reply rust/core-lib/src/index_set.rs]: :ok_hand:

File: rust/core-lib/src/plugins/catalog.rs (hunk 4 above)
Comment (PsiACE) [reply rust/core-lib/src/plugins/catalog.rs]: Looks feasible, feedback later.

File: rust/core-lib/src/tabs.rs (hunk 5 above)
Comment (PsiACE) [reply rust/core-lib/src/tabs.rs]: Does this mean that `manifest.clone()` -> `manifest`?
Looks feasible, feedback later.

File: rust/rope/src/multiset.rs (hunk 6 above)
Comment (PsiACE) [reply rust/rope/src/multiset.rs]: :ok_hand:

File: rust/rope/src/rope.rs (hunk 7 above)
Comment (PsiACE) [reply rust/rope/src/rope.rs]: :ok_hand:

File: rust/rope/src/spans.rs (hunk 8 above)
Comment (PsiACE) [reply rust/rope/src/spans.rs]: :ok_hand:

File: rust/unicode/src/lib.rs (hunk 11 above)
Comment (PsiACE) [reply rust/unicode/src/lib.rs]: :ok_hand:

File: rust/unicode/src/lib.rs (hunk 12 above)
Comment (PsiACE) [reply rust/unicode/src/lib.rs]: :ok_hand:

File: rust/rpc/src/error.rs (hunk 10 above)
Comment (PsiACE) [reply rust/rpc/src/error.rs]: Same as above.

File: rust/core-lib/src/rpc.rs (hunk 9 above)
Comment (PsiACE) [reply rust/core-lib/src/rpc.rs]: Just remove it. Although I don't think this is a problem.

**Comment by PsiACE** [comment]
Sorry I pushed it directly, but it passed all tests.

File: rust/core-lib/src/index_set.rs (hunk 1 above)
Comment (cmyr) [reply rust/core-lib/src/index_set.rs]: oops yep my mistake!

File: rust/core-lib/src/rpc.rs (hunk 9 above)
Comment (cmyr) [reply rust/core-lib/src/rpc.rs]: it's not, we just prefer to minimize ignoring things. 🤷‍♂

File: rust/core-lib/src/plugins/catalog.rs [hunk 13]
```diff
@@ -116,7 +116,6 @@ fn find_all_manifests(paths: &[PathBuf]) -> Vec<PathBuf> {
             dir.flat_map(|item| item.map(|p| p.path()).ok())
                 .map(|dir| dir.join("manifest.toml"))
                 .filter(|f| f.exists())
-                .for_each(|f| manifest_paths.push(f.to_owned()))
```
Comment (cmyr) [inline rust/core-lib/src/plugins/catalog.rs]: This is a mistake; we do need this line, we just can replace `f.to_owned()` with `f`.

File: rust/core-lib/src/config.rs [hunk 14]
```diff
@@ -12,6 +12,8 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 
+#![allow(clippy::redundant_clone)]
```
Comment (cmyr) [inline rust/core-lib/src/config.rs]: I think we can get rid of this now?

File: rust/core-lib/src/plugins/catalog.rs (hunk 13 above)
Comment (PsiACE) [reply rust/core-lib/src/plugins/catalog.rs]: :ok_hand: Sorry it's my wrong.

File: rust/core-lib/src/config.rs (hunk 14 above)
Comment (PsiACE) [reply rust/core-lib/src/config.rs]: We have `domain.clone ()` on L469, L496 and `value.to_owned ()` on L760.

Change to `domain` & `value`.

**Comment by PsiACE** [comment]
Everything looks ok.
