### PR TITLE
Only check whitespace when opening an existing file

### LINKED ISSUE #900: Only check whitespace when opening an existing file
Currently, we check a file's whitespace when creating a new empty buffer, which will be a noop but causes spurious warnings in the  view. Instead we should only check whitespace when opening an existing buffer.

This should be a quick fix for someone; a good place to start is by searching for the text, "set_user_config failed to update config, no tables were returned" in `core-lib/src/tabs.rs`.

### PR DESCRIPTION
**Pull request by YangKeao**
## Summary
Fix #900. Add a tag `is_existing_file` to `pending_views` and detect_whitespace according to it.

## Related Issues
closes #900

### CODE REVIEW

File: rust/core-lib/src/tabs.rs [hunk 1]
```diff
@@ -566,11 +568,16 @@ impl CoreState {
 
     fn finalize_new_views(&mut self) {
         let to_start = mem::replace(&mut self.pending_views, Vec::new());
-        to_start.iter().for_each(|(id, config)| {
-            let modified = self.detect_whitespace(*id, config);
-            let config = modified.as_ref().unwrap_or(config);
-            let mut edit_ctx = self.make_context(*id).unwrap();
-            edit_ctx.finish_init(&config);
+        to_start.iter().for_each(|(id, config, is_existing_file)| {
+            if *is_existing_file {
```
Comment (cmyr) [inline rust/core-lib/src/tabs.rs]: instead of passing through `is_existing_file`, we could just do,

```rust
let has_contents = self.editors.get(&buffer_id)
    .map(|e| !e.get_buffer().is_empty())
    .unwrap_or_default();
if has_contents {
    // ...
} else {
    // ...
}
```

This might be easier? It means less state to worry about.

File: rust/core-lib/src/tabs.rs [hunk 2]
```diff
@@ -370,8 +370,10 @@ impl CoreState {
         let view_id = self.next_view_id();
         let buffer_id = self.next_buffer_id();
 
+        let mut is_existing_file = false;
+
         let rope = match path.as_ref() {
-            Some(p) => self.file_manager.open(p, buffer_id)?,
+            Some(p) => {is_existing_file = true; self.file_manager.open(p, buffer_id)?},
```
Comment (cmyr) [inline rust/core-lib/src/tabs.rs]: oh also: `rustfmt` (which i'll turn on soon) is going to make us put this on separate lines.

File: rust/core-lib/src/tabs.rs (hunk 1 above)
Comment (YangKeao) [reply rust/core-lib/src/tabs.rs]: Yes. So that only when open an non-empty file whitespace will be checked.

File: rust/core-lib/src/tabs.rs [hunk 3]
```diff
@@ -567,10 +568,19 @@ impl CoreState {
     fn finalize_new_views(&mut self) {
         let to_start = mem::replace(&mut self.pending_views, Vec::new());
         to_start.iter().for_each(|(id, config)| {
-            let modified = self.detect_whitespace(*id, config);
-            let config = modified.as_ref().unwrap_or(config);
-            let mut edit_ctx = self.make_context(*id).unwrap();
-            edit_ctx.finish_init(&config);
+            let buffer_id = self.views.get(&id).map(|v| v.borrow().get_buffer_id()).unwrap();
```
Comment (LiHRaM) [inline rust/core-lib/src/tabs.rs]: The `detect_whitespace` method already fetches the `buffer_id` - if you make the check over there, you can just return `None` on false and keep `finalize_new_views` simpler?

Comment (cmyr) [reply rust/core-lib/src/tabs.rs]: That's a good point, this becomes basically a one-liner in `detect_whitespace`: 
```rust
if editor.borrow().get_buffer().is_empty() { return None; }
```

Comment (YangKeao) [reply rust/core-lib/src/tabs.rs]: Thanks for your advice!

File: rust/core-lib/src/tabs.rs [hunk 4]
```diff
@@ -577,6 +578,14 @@ impl CoreState {
...
         let buffer_id = self.views.get(&id).map(|v| v.borrow().get_buffer_id())?;
+        if self.editors.get(&buffer_id)
+            .map(|e| {
+                e.borrow().get_buffer().len() == 0
+            })
+            .unwrap_or_default() {
+            return None;
+        }
+
         let editor = self.editors.get(&buffer_id).expect("existing buffer_id must have corresponding editor");
```
Comment (cmyr) [inline rust/core-lib/src/tabs.rs]: we already get the editor here; if we move the check down below this line, it's just:

```rust
if editor.get_buffer().is_empty() {
    return None;
}
```

Comment (cmyr) [reply rust/core-lib/src/tabs.rs]: maybe you were thinking that this handles the case when there is no editor better?

Comment (cmyr) [reply rust/core-lib/src/tabs.rs]: @YangKeao thoughts on this?

Comment (cmyr) [reply rust/core-lib/src/tabs.rs]: @YangKeao 😁

**Comment by YangKeao** [comment]
Sorry for replying late :cry:.

**Comment by YangKeao** [comment]
Sorry, there are some bugs. I will fix them.

**Comment by cmyr** [comment]
No problem, thanks for the fix! It looks like you'll also need to run rustfmt on this, it's something we just added to CI.

If you're interested in continuing to work on xi stuff when you have time, I would be happy to add you to the xi-editor organization?

**Comment by YangKeao** [comment]
Aha, I am very interested in rust and xi-editor and willing to work on it. Thank you :smile:

**Comment by cmyr** [comment]
Okay, sent. I'm done for the day but will check in on this tomorrow. ☀️
