### PR TITLE
Fixing casting error from u32 to u64

### LINKED ISSUE #992: fix xi-trace clippy lints
xi-trace is currently failing the clippy section of CI on windows. See [this job](https://travis-ci.com/xi-editor/xi-editor/jobs/159153709) for an example.

This should be as simple as making the changes suggested in the link above, and making sure that clippy passes on windows.

### PR DESCRIPTION
**Pull request by ThisisGurwinder**
## Summary
We were casting GetCurrentProcessId() as u64 which was giving error.

## Related Issues
     closes #992 

## Review Checklist

- [x] I have responded to reviews and made changes where appropriate.
- [x] I have tested the code with `cargo test --all` / `./rust/run_all_checks`.
- [x] I have updated comments / documentation related to the changes I made.
- [x] I have rebased my PR branch onto xi-editor/master.

### CODE REVIEW

**Comment by jansol** [comment]
`u64::from()` turns the value into an `u64` so there is no need for the `as u64` anymore.

File: rust/trace/src/sys_tid.rs [hunk 1]
```diff
@@ -86,5 +86,5 @@ pub fn current_tid() -> Result<u64, libc::c_int> {
         fn GetCurrentThreadId() -> libc::c_ulong;
     }
 
-    unsafe { Ok(GetCurrentThreadId() as u64) }
+    unsafe { Ok(u64::from(GetCurrentProcessId())) as u64 }
```
Comment (jansol) [inline rust/trace/src/sys_tid.rs]: This does not even compile. The fn in question returns a Result but you are forcibly casting it to a plain u64.

Comment (jansol) [reply rust/trace/src/sys_tid.rs]: This is also trying to call the wrong function now. `GetCurrentProcessId` is not available here, should be `GetCurrentThreadId` like it originally was.

File: rust/trace/src/sys_pid.rs [hunk 2]
```diff
@@ -37,5 +37,5 @@ pub fn current_pid() -> u64 {
         fn GetCurrentProcessId() -> libc::c_ulong;
     }
 
-    unsafe { GetCurrentProcessId() as u64 }
+    unsafe { u64::from(GetCurrentProcessId()) as u64 }
```
Comment (jansol) [inline rust/trace/src/sys_pid.rs]: The `as u64` here is also unnecessary now.

**Comment by ThisisGurwinder** [comment]
@jansol I didn't realized that we don't have windows platform in testing pipeline.I have tested this explicitly on windows platform now and all test passes. Can you please review the changes again?

**Comment by cmyr** [comment]
This does the trick, thanks @ThisisGurwinder!

**Comment by ThisisGurwinder** [comment]
Thanks @jansol @cmyr 
I really enjoyed this and I am looking forward to contribute more 👍 :)

**Comment by cmyr** [comment]
I guess I need to open more issues. 😏
